### PR TITLE
Pundit

### PR DESCRIPTION
**Pull request by pwestman82**

### CODE REVIEW

**Comment by gabrielecanepa** [comment]
[Add pundit](https://trello.com/c/W5BDnRD3/15-add-pundit)

**Comment by pwestman82** [comment]
To be reviewed as a group tomorrow

**Comment by gabrielecanepa** [comment]
Blocked for now, since it would give us troubles with the other features we are developing. Let's do it all together tomorrow @pwestman82 @jones-sam @mollycalypso @Savina05

**Comment by gabrielecanepa** [comment]
I closed this one, we will redo it all together 🙂  @pwestman82 @jones-sam @mollycalypso @Savina05

**Pull request closed without merging**
